apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ecommerce
spec:
  replicas: 1 #jumlah pods rabbitmq yang akan berjalan
  selector:
    matchLabels:
      app: rabbitmq 
  template:
    metadata:
      labels:
        app: rabbitmq #label yang akan disematkan kedalam pods rabbitmq
    spec:
      containers:
      - name:  rabbitmq
        image: rabbitmq:3.8-management-alpine #image yang digunakan rabbitmq
