apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ecommerce
spec:
  type: ClusterIP
  ports:
  - name: amqp #port yang digunakan untuk app rabbitmq
    port: 5672
    targetPort: 5672
  - name: web #port yang digunakan untuk mengakses rabbitmq
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq