apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: karsajobs
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo
        name: mysql
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 22017
          name: mongo
        volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
        - name: mongo-config
          mountPath: /config
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
      volumes:
      - name: mongo-pv
        persistentVolumeClaim:
          claimName: mongo-pvc