apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: karsajobs
spec:
  type: ClusterIP
  ports:
  - port: 27017 #port yang digunakan oleh service mongodb
    targetPort: 27017
  selector:
    app: mongo