apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ecommerce
spec:
  replicas: 1 #jumlah pods yang dihasilkan
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order #label yang menempel ke pods
    spec:
      containers:
      - name:  order
        image: farrasyakila/order-service:latest
        env : 
        - name: PORT
          value: "3000"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq.ecommerce.svc.cluster.local:5672"
        resources:
          limits:
            cpu: "0.4"
            memory: 500Mi
          requests:
            cpu: "0.1"
            memory: 150Mi
        ports:
        - containerPort: 3000