apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: ecommerce
spec:
  replicas: 1 #Jumlah pods yang digunakan
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name:  shipping
        image: farrasyakila/shipping-service:latest
        env : 
        - name: PORT
          value: "3001"
        - name: AMQP_URL #variable yang digunakan untuk mendapatkan akses ke rabbitmq
          value: "amqp://guest:guest@rabbitmq.ecommerce.svc.cluster.local:5672"
        resources:
          limits:
            cpu: "0.4"
            memory: 500Mi
          requests:
            cpu: "0.1"
            memory: 150Mi
        ports:
        - containerPort: 3001