apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: ecommerce
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001 #port yang digunakan service shipping
    targetPort: 3001
  selector:
    app: shipping