# This is a basic workflow to help you get started with Actions

name: CI Karsajobs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "karsajob" branch
  push:
    branches: 
      - karsajobs
  pull_request:
    branches: 
        - karsajobs

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint-dockerfile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # step to Install hadolint 
      - name: Install Hadolint
        run: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

      # melakukan pengecekan pada dockerfile
      - name: Lint Dockerfile
        run : hadolint Dockerfile
        
  #next step menjalankan unit test untuk backend
  test-app:
    name: Unit test Backend
    runs-on: ubuntu-latest
    
    steps:
      # melakukan checkout repository dari branch yang sedang berjalan
      - name: Checkout repository
        uses: actions/checkout@v3

      # install golang di runner github untuk menjalankan command go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15' 

      # menjalankan command untuk unit testing di golang
      - name: Run Go Unit Tests
        run: go test -v -short --count=1 $(go list ./...)

  #next step untuk melakukan build dan push docker image
  build-app-karsajobs:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint-dockerfile, test-app] #job hanya dijalankan jika kedua step ini berhasil
    
    steps:
      # melakukan checkout repository dari branch yang sedang berjalan
      - name: Checkout repository
        uses: actions/checkout@v3

      # menentukan tools yang akan digunakan untuk build image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # login akun docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # melakukan build image dan push image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: farrasyakila/karsajobs:latest

